name: palestinian_ministry_endowments
description: A comprehensive enterprise-grade mobile and web application for the Palestinian Ministry of Endowments and Religious Affairs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

  # State Management
  flutter_riverpod: ^3.0.1

  # Backend & Database
  supabase_flutter: ^2.0.0

  # UI & Design
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.1.0

  # Maps & Location
  google_maps_flutter: ^2.5.0
  location: ^8.0.1
  geocoding: ^4.0.0

  # Media & Files
  image_picker: ^1.0.4
  file_picker: ^10.3.3
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0
  video_player: ^2.8.1

  # Charts & Analytics
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^31.1.21

  # Notifications
  flutter_local_notifications: ^19.4.2

  # Storage & Caching
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking
  dio: ^5.4.0
  connectivity_plus: ^7.0.0

  # Utils
  uuid: ^4.2.1
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  url_launcher: ^6.2.2
  share_plus: ^12.0.0
  flutter_dotenv: ^5.1.0

  # PDF & Documents
  pdf: ^3.10.7
  printing: ^5.11.1
  open_file: ^3.3.2

  # Forms & Validation
  reactive_forms: ^18.1.1

  # Animation
  lottie: ^3.3.2
  flutter_staggered_animations: ^1.1.1

  # JSON Serialization
  json_annotation: ^4.9.0

  # Date & Time
  timezone: ^0.10.1

  freezed_annotation: ^3.1.0

  http: any
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^3.2.3

  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/
    - assets/fonts/
    - .env

  # Fonts
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated/l10n